# The Titanic Survival Prediction

## Imports and Data Loading

In [1]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier

In [2]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/heptapod/titanic/train_and_test2.csv

In [3]:
df = pd.read_csv("/kaggle/input/datasets/heptapod/titanic/train_and_test2.csv")
df.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

## Preprocessing and Preparing x and y

In [4]:
x = df[["Pclass","Sex","Age","Fare"]]
x.head()

   Pclass  Sex   Age     Fare
0       3    0  22.0   7.2500
1       1    1  38.0  71.2833
2       3    1  26.0   7.9250
3       1    1  35.0  53.1000
4       3    0  35.0   8.0500

In [5]:
x.describe()

            Pclass          Sex          Age         Fare
count  1309.000000  1309.000000  1309.000000  1309.000000
mean      2.294882     0.355997    29.503186    33.281086
std       0.837836     0.478997    12.905241    51.741500
min       1.000000     0.000000     0.170000     0.000000
25%       2.000000     0.000000    22.000000     7.895800
50%       3.000000     0.000000    28.000000    14.454200
75%       3.000000     1.000000    35.000000    31.275000
max       3.000000     1.000000    80.000000   512.329200

In [6]:
x.shape

(1309, 4)

In [7]:
x.Sex.count

<bound method Series.count of 0       0
1       1
2       1
3       1
4       0
       ..
1304    0
1305    1
1306    0
1307    0
1308    0
Name: Sex, Length: 1309, dtype: int64>

### Encoding the Sex column

In [8]:
y = df['2urvived']

#encoding Sex with one hot encoder, this is better and using label encoder before it is depricated now
ct = ColumnTransformer([("Sex", OneHotEncoder(drop="first"), [1])], remainder="passthrough")
x = ct.fit_transform(x)
x

array([[ 0.    ,  3.    , 22.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  7.925 ],
       ...,
       [ 0.    ,  3.    , 38.5   ,  7.25  ],
       [ 0.    ,  3.    , 28.    ,  8.05  ],
       [ 0.    ,  3.    , 28.    , 22.3583]])

### Making a dataframe with column names

In [9]:
# to see the column name, i always do the following thing
feature_columns = ct.get_feature_names_out()
features = pd.DataFrame(x, columns=feature_columns)
features.head()

   Sex__Sex_1  remainder__Pclass  remainder__Age  remainder__Fare
0         0.0                3.0            22.0           7.2500
1         1.0                1.0            38.0          71.2833
2         1.0                3.0            26.0           7.9250
3         1.0                1.0            35.0          53.1000
4         0.0                3.0            35.0           8.0500

## Training the model

### Train Test Split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y , train_size=0.8)

### Model fitting

In [11]:
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

DecisionTreeClassifier()

### Checking the Score

In [12]:
model.score(x_test, y_test)

0.7557251908396947